//~ Revision: 96, Copyright (C) 2016-2018: Willem Vree, contributions Stéphane David.
//~ This program is free software; you can redistribute it and/or modify it under the terms of the
//~ GNU General Public License as published by the Free Software Foundation; either version 2 of
//~ the License, or (at your option) any later version.
//~ This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
//~ without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//~ See the GNU General Public License for more details. <http://www.gnu.org/licenses/gpl.html>.
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,e,q){if(q.get||q.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[e]=q.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var e=0;return $jscomp.iteratorPrototype(function(){return e<a.length?{done:!1,value:a[e++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,e){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var q=0,b={next:function(){if(q<a.length){var r=q++;return{value:e(r,a[r]),done:!1}}b.next=function(){return{done:!0,value:void 0}};return b.next()}};b[Symbol.iterator]=function(){return b};return b};
$jscomp.polyfill=function(a,e,q,b){if(e){q=$jscomp.global;a=a.split(".");for(b=0;b<a.length-1;b++){var r=a[b];r in q||(q[r]={});q=q[r]}a=a[a.length-1];b=q[a];e=e(b);e!=b&&null!=e&&$jscomp.defineProperty(q,a,{configurable:!0,writable:!0,value:e})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6-impl","es3");
$jscomp.polyfill("Math.log10",function(a){return a?a:function(a){return Math.log(a)/Math.LN10}},"es6-impl","es3");$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var e=a[Symbol.iterator];return e?e.call(a):$jscomp.arrayIterator(a)};$jscomp.EXPOSE_ASYNC_EXECUTOR=!0;$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function e(){this.batch_=null}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;e.prototype.asyncExecute=function(d){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(d);return this};e.prototype.asyncExecuteBatch_=function(){var d=this;this.asyncExecuteFunction(function(){d.executeBatch_()})};var q=$jscomp.global.setTimeout;e.prototype.asyncExecuteFunction=function(d){q(d,0)};e.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var d=
this.batch_;this.batch_=[];for(var a=0;a<d.length;++a){var b=d[a];delete d[a];try{b()}catch(C){this.asyncThrow_(C)}}}this.batch_=null};e.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var b=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var d=this.createResolveAndReject_();try{a(d.resolve,d.reject)}catch(t){d.reject(t)}};b.prototype.createResolveAndReject_=function(){function a(a){return function(d){t||(t=!0,a.call(b,d))}}var b=this,t=
!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};b.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof b)this.settleSameAsPromise_(a);else{var d;a:switch(typeof a){case "object":d=null!=a;break a;case "function":d=!0;break a;default:d=!1}d?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};b.prototype.resolveToNonPromiseObj_=function(a){var d=void 0;try{d=a.then}catch(t){this.reject_(t);return}"function"==
typeof d?this.settleSameAsThenable_(d,a):this.fulfill_(a)};b.prototype.reject_=function(a){this.settle_(2,a)};b.prototype.fulfill_=function(a){this.settle_(1,a)};b.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};b.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=this.onSettledCallbacks_,b=0;b<a.length;++b)a[b].call(),
a[b]=null;this.onSettledCallbacks_=null}};var r=new e;b.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};b.prototype.settleSameAsThenable_=function(a,b){var d=this.createResolveAndReject_();try{a.call(b,d.resolve,d.reject)}catch(C){d.reject(C)}};b.prototype.then=function(a,e){function d(a,b){return"function"==typeof a?function(b){try{C(a(b))}catch(R){q(R)}}:b}var C,q,r=new b(function(a,b){C=a;q=b});this.callWhenSettled_(d(a,C),
d(e,q));return r};b.prototype["catch"]=function(a){return this.then(void 0,a)};b.prototype.callWhenSettled_=function(a,b){function d(){switch(e.state_){case 1:a(e.result_);break;case 2:b(e.result_);break;default:throw Error("Unexpected state: "+e.state_);}}var e=this;null==this.onSettledCallbacks_?r.asyncExecute(d):this.onSettledCallbacks_.push(function(){r.asyncExecute(d)})};b.resolve=function(a){return a instanceof b?a:new b(function(b,d){b(a)})};b.reject=function(a){return new b(function(b,d){d(a)})};
b.race=function(a){return new b(function(d,e){for(var q=$jscomp.makeIterator(a),t=q.next();!t.done;t=q.next())b.resolve(t.value).callWhenSettled_(d,e)})};b.all=function(a){var d=$jscomp.makeIterator(a),e=d.next();return e.done?b.resolve([]):new b(function(a,q){function t(b){return function(d){r[b]=d;C--;0==C&&a(r)}}var r=[],C=0;do r.push(void 0),C++,b.resolve(e.value).callWhenSettled_(t(r.length-1),q),e=d.next();while(!e.done)})};$jscomp.EXPOSE_ASYNC_EXECUTOR&&(b.$jscomp$new$AsyncExecutor=function(){return new e});
return b},"es6-impl","es3");var xmlplay_VERSION=96,instUrl="",withRT=1,instTab={};
(function(){function a(a,b,w){function k(a){var h,k,l,g,b,f,E={},c,z={},w=[18,20,22,24,26,28];a=a.split("\n");for(h=0;h<a.length;++h)if(k=a[h],0<=k.indexOf("strings")&&(l=k.match(/V:\s*(\S+).*strings\s*=\s*(\S+)/)))c=l[1],E[c]={},l[2].split(",").forEach(function(a,l){g=a[0];b=12*parseInt(a[1]);f=b+[0,2,4,5,7,9,11]["CDEFGAB".indexOf(g)]+12;E[c][w[l]]=f}),z[c]=0<=k.indexOf("diafret");return[E,z]}function n(a){var k,b,l,g,f={};a=a.split("\n");for(k=0;k<a.length;++k)if(b=a[k],0<=b.indexOf("%%map")&&(l=
b.match(/%%map *(\S+) *(\S+).*midi=(\d+)/)))b=l[1],g=l[2],l=l[3],f[b+g]=parseInt(l);return f}function c(a){var k={diamond:1,triangle:1,square:1,normal:1},b=['%%beginsvg\n<defs>\n<text id="x" x="-3" y="0">&#xe263;</text>\n<text id="x-" x="-3" y="0">&#xe263;</text>\n<text id="x+" x="-3" y="0">&#xe263;</text>\n<text id="normal" x="-3.7" y="0">&#xe0a3;</text>\n<text id="normal-" x="-3.7" y="0">&#xe0a3;</text>\n<text id="normal+" x="-3.7" y="0">&#xe0a4;</text>\n<g id="circle-x"><text x="-3" y="0">&#xe263;</text><circle r="4" class="stroke"/></g>\n<g id="circle-x-"><text x="-3" y="0">&#xe263;</text><circle r="4" class="stroke"/></g>\n<path id="triangle" d="m-4 -3.2l4 6.4 4 -6.4z" class="stroke" style="stroke-width:1.4"/>\n<path id="triangle-" d="m-4 -3.2l4 6.4 4 -6.4z" class="stroke" style="stroke-width:1.4"/>\n<path id="triangle+" d="m-4 -3.2l4 6.4 4 -6.4z" class="stroke" style="fill:#000"/>\n<path id="square" d="m-3.5 3l0 -6.2 7.2 0 0 6.2z" class="stroke" style="stroke-width:1.4"/>\n<path id="square-" d="m-3.5 3l0 -6.2 7.2 0 0 6.2z" class="stroke" style="stroke-width:1.4"/>\n<path id="square+" d="m-3.5 3l0 -6.2 7.2 0 0 6.2z" class="stroke" style="fill:#000"/>\n<path id="diamond" d="m0 -3l4.2 3.2 -4.2 3.2 -4.2 -3.2z" class="stroke" style="stroke-width:1.4"/>\n<path id="diamond-" d="m0 -3l4.2 3.2 -4.2 3.2 -4.2 -3.2z" class="stroke" style="stroke-width:1.4"/>\n<path id="diamond+" d="m0 -3l4.2 3.2 -4.2 3.2 -4.2 -3.2z" class="stroke" style="fill:#000"/>\n</defs>\n%%endsvg'],
l,g,f,c="default",E={"default":[]};a=a.split("\n");for(l=0;l<a.length;++l)if(g=a[l],0<=g.indexOf("I:percmap")&&(g=g.split(" "),f=g[4],f in k&&(f=f+"+,"+f),g="%%map perc"+c+" "+g[1]+" print="+g[2]+" midi="+g[3]+" heads="+f,E[c].push(g)),0<=g.indexOf("V:")&&(f=g.match(/V:\s*(\S+)/)))c=f[1],c in E||(E[c]=[]);for(c in E)b=b.concat(E[c]);for(l=0;l<a.length;++l)g=a[l],0<=g.indexOf("I:percmap")||(0<=g.indexOf("V:")||0<=g.indexOf("K:")?((f=g.match(/V:\s*(\S+)/))&&(c=f[1]),0==E[c].length&&(c="default"),b.push(g),
0<=g.indexOf("perc")&&-1==g.indexOf("map=")&&(g+=" map=perc"),0<=g.indexOf("map=perc")&&0<E[c].length&&b.push("%%voicemap perc"+c),0<=g.indexOf("map=off")&&b.push("%%voicemap")):b.push(g));return b.join("\n")}w&&(0<=a.indexOf("I:percmap")&&(a=c(a)),0<=a.indexOf("%%map")&&(la=n(a)),0<=a.indexOf(" strings")&&k(a));F=b;M=0;var z=function(){q(a,b,w)};w?e(a,z):z()}function e(a,b){function k(a){var b=[];a.forEach(function(a,k){b[a.st]?b[a.st].push(k):b[a.st]=[k];a.clef.clef_octave&&(N[k]=a.clef.clef_octave);
G[k]=a.midictl&&a.midictl[7];void 0==G[k]&&(G[k]=100);H[k]=a.midictl&&a.midictl[10];void 0==H[k]&&(H[k]=64);f[k]=a.instr?a.instr:0});return b}var A,n="",c=[3,0,4,1,5,2,6],z=[0,2,4,5,7,9,11];I=[];N=[];K=120;G=[];H=[];var f=[];A=new Abc({img_out:null,errmsg:function(a,k,b){n+=a+"\n"},read_file:function(a){return""},anno_start:null,get_abcmodel:function(h,p,l){function g(a,k){w[a]=[0,0,0,0,0,0,0];E[a]={};n[a]=k;var b=0<=k;(b?c.slice(0,k):c.slice(k)).forEach(function(k){w[a][k]+=b?1:-1})}var w={},A={"-2":-2,
"-1":-1,0:0,1:1,2:2,3:0},E={},n={},d={},e={ppp:30,pp:45,p:60,mp:75,mf:90,f:105,ff:120,fff:127},D=[],q;l=p[0].meter.a_meter;l.length&&parseInt(l[0].top);for(u=0;u<p.length;++u)g(u,p[u].key.k_sf),d[u]={};l={};ma=p.length;S=k(p);for(var m=h;m;m=m.ts_next){var r,t,v,y=[],u;switch(m.type){case 14:h=m.tempo_notes.reduce(function(a,k){return a+k});K=m.tempo*h/384;break;case 10:t={t:m.time,mnum:-1,dur:m.dur};y.push(t);I.push({t:m.time,ix:m.istart,v:m.v,ns:y,inv:m.invis,tmp:K});break;case 8:var B=f[m.v];"p"==
m.p_v.clef.clef_type&&(B+=128);for(h=0;h<m.notes.length;++h){p=m.notes[h];r=p.pit+19;u=m.v;m.a_dd&&m.a_dd.forEach(function(a){(q=e[a.name])&&S[m.st].forEach(function(a){D[a]=q})});q=D[u]||60;N[u]&&(r+=N[u]);t=Math.floor(r/7);v=r%7;void 0!=p.acc&&(E[u][r]=A[p.acc]);t=12*t+z[v]+(r in E[u]?E[u][r]:w[u][v]);v=m.p_v.map;if(128<=B&&"MIDIdrum"!=v){var C=a.substring(m.istart,m.iend),C=C.match(/[=_^]*[A-Ga-g]/)[0];(v=la[v+C])&&(t=v)}t=128*B+t;l[t]=1;t={t:m.time,mnum:t,dur:m.dur,velo:q};r in d[u]?(d[u][r].dur+=
m.dur,0==p.ti1&&delete d[u][r]):(0!=p.ti1&&(d[u][r]=t),y.push(t))}if(0==y.length)break;I.push({t:m.time,ix:m.istart,v:m.v,ns:y,stf:m.st,tmp:K});break;case 5:g(m.v,m.k_sf);break;case 0:g(m.v,n[m.v]);I.push({t:m.time,ix:m.istart,v:m.v,bt:m.bar_type,tx:m.text});break;case 16:m.instr&&(f[m.v]=m.instr),7==m.ctrl&&(G[m.v]=m.val),10==m.ctrl&&(H[m.v]=m.val)}}T.forEach(function(a){var k=a.parentNode;k&&k.removeChild(a)});O=[];A="#f9f #3cf #c99 #f66 #fc0 #cc0 #ccc".split(" ");for(h=0;h<ma;++h)d=1<<h&0?"0":
"",u=document.createElementNS("http://www.w3.org/2000/svg","rect"),u.setAttribute("fill",A[h%A.length]+d),u.setAttribute("fill-opacity","0.5"),u.setAttribute("width","0"),T.push(u),O.push(-1);b();null!=x?sa(l):alert("Your browser has no Web Audio API -> no playback.")}});A.tosvg("play","%%play");A.tosvg("abc2svg",a);""==n&&(n="no error");console.log(n)}function q(k,e,w){function A(b){var c,f,l,h,z;b.stopPropagation();z=J.indexOf(this);if(!w||0>z)t(0),a(k,e,1);else if(l=b.clientX,l-=this.getBoundingClientRect().left,
h=l*U,h<g||h>D)t(0);else{V||t(1);c=(b.clientY-this.getBoundingClientRect().top)*U;l=W[z];for(b=0;b<l.length;b++)if(l[b]>c){X=b;break}for(b=0;b<v.length;++b)if(c=v[b].xy)if(l=v[b].vce,-1!=S[X].indexOf(l)&&(f=c[0],l=c[1],c=c[3],!(f<z)&&h<parseFloat(l)+c)){y=b;for(h=v[b].t;v[b]&&v[b].t==h;)r(v[b]),b+=1;break}}}var n,c="",z="",f=0;y=0;Y={};W=[];var h={},p,l,g=1E3,D=0;X=0;if(k&&(n=new Abc({imagesize:'width="100%"',img_out:function(a){-1!=a.indexOf("<svg")&&(W[f]=Object.keys(h),h={},f+=1,p<g&&(g=p),l>D&&
(D=l));c+=a},errmsg:function(a,b,k){z+=a+"\n"},read_file:function(a){return""},anno_start:function(a,b,k,c,g,z,m){if("note"==a||"rest"==a)c=n.ax(c).toFixed(2),g=n.ay(g).toFixed(2),m=n.ah(m),Y[b]=[f,c,g,z,m];"bar"==a&&(g=n.ay(g),m=n.ah(m),g=Math.round(g+m),h[g]=1,l=n.ax(c),p=n.ax(0))},get_abcmodel:null}),n.tosvg("abc2svg",k),""==z&&(z="no error\n"),console.log(z),c)){F.innerHTML=c;J=Array.prototype.slice.call(F.getElementsByTagName("svg"));var q=Array.prototype.slice.call(F.getElementsByClassName("g"));
P=q.length?q:J;b();J.forEach(function(a){R(a,"click",A)});w&&d()}}function b(){if(0!=J.length){var a,b,w,d=J[0];a=d.getBoundingClientRect().width;try{b=d.viewBox.baseVal.width}catch(n){b=a}w=(w=P[0].transform)?w.baseVal:[];w=w.length?w.getItem(0).matrix.a:1;U=b/w/a}}function r(a){function b(a,b){h=a.getBoundingClientRect();e=b.getBoundingClientRect();if(h.top<e.top||0>h.top||h.bottom>e.bottom||h.bottom>g)b.scrollTop=b==l?h.top-e.top:b.scrollTop+(h.top-e.top)}var k,d,n,c,z,f,h,p,l,g,e;f=T[a.vce];(k=
a.xy)?(d=k[0],n=k[1],c=k[2],z=k[3],k=k[4],a.inv&&(k=z=0),d!=O[a.vce]&&((p=f.parentNode)&&p.removeChild(f),p=P[d],p.insertBefore(f,p.firstChild),O[a.vce]=d,a=P[d],l=document.scrollingElement,g=document.documentElement.clientHeight,F.scrollHeight>F.clientHeight&&b(a,F),b(a,l)),f.setAttribute("x",n),f.setAttribute("y",c),f.setAttribute("width",z),f.setAttribute("height",k)):(f.setAttribute("width",0),f.setAttribute("height",0))}function d(){var a=0<y?v[y].t:0;v=[];Z={};var b=1,d=0,e=0,n=0,c=0,z=0,f,
h;for(f=0;f<I.length;++f){h=I[f];if(h.bt&&0==h.v){if(h.t in Z&&":"==h.bt[0])continue;if(1==b&&":"==h.bt[0]&&h.t>n){f=e-1;b=2;d+=h.t-n;continue}2==b&&":"==h.bt[0]&&h.t>n&&(b=1);1==b&&":"==h.bt[h.bt.length-1]&&(e=f,n=h.t);c&&(h.tx||"|"!=h.bt)&&(c=0,d-=h.t-z);2==b&&"1"==h.tx&&(c=1,z=h.t)}c||(h.bt?Z[h.t]=1:v.push({t:h.t+d,xy:Y[h.ix],ns:h.ns,vce:h.v,inv:h.inv,tmp:h.tmp}))}for(y=0;y<v.length&&(h=v[y],!(h.t>=a)||h.inv);++y);y==v.length&&--y;r(v[y])}function ja(){if(x){for(var a=1E3*x.currentTime,b=0,d;0==
b;){var e=v[y];d=156.25/e.tmp;y==v.length-1?(y=-1,b=e.ns[0].dur+1E3):(b=v[y+1].t,b=(b-e.t)*d);e.ns.forEach(function(b,k){d=192>=b.dur?1.3*d:1.1*d;var c=b.mnum,f=b.dur*d,h=e.vce,p=b.velo;if(-1!=c){var l=c>>7;if(l in aa){var g=c%128,n=a/1E3,c=(f-1)/1E3,w,q,r,t,A,v;if(f=ba[l][g]){var D=x.createBufferSource(),m=f.useflt,y=f.uselfo,B=f.useenv,C=G[h]/127,h=(H[h]-64)/64;D.buffer=f.buffer;f.loopStart&&(D.loop=!0,D.loopStart=f.loopStart,D.loopEnd=f.loopEnd);D.playbackRate.value=ca[l][g];y&&(q=x.createOscillator(),
q.frequency.value=f.lfofreq,l=x.createGain(),l.gain.value=f.lfo2vol,q.connect(l),w=x.createGain(),w.gain.value=1,l.connect(w.gain),l=x.createGain(),l.gain.value=f.lfo2ptc,q.connect(l),l.connect(D.detune));if(m){var F=x.createBiquadFilter();F.type="lowpass";F.frequency.value=f.filter}if(B){var u=1,l=x.createGain();l.gain.setValueAtTime(0,n);l.gain.linearRampToValueAtTime(u,n+f.envatt);g=f.envhld;A=f.envdec;c>g&&(l.gain.setValueAtTime(u,n+g),c<A?(v=c-g,A=v/(A-g)*f.envsus):(v=A-g,A=f.envsus),u*=A,l.gain.linearRampToValueAtTime(u,
n+g+v));l.gain.setValueAtTime(u,n+c);g=n+c+u*f.envrel;l.gain.linearRampToValueAtTime(0,g);r=x.createConstantSource();r.offset.value=f.env2flt;r.connect(l);l.connect(F.detune)}Q&&(t=x.createStereoPanner(),t.pan.value=h);u=p*C*f.atten*ua;0==u&&(u=1E-5);p=x.createGain();p.gain.setValueAtTime(1E-5,n);p.gain.exponentialRampToValueAtTime(u,n+f.attack);g=f.hold;A=f.decay;c>g&&(p.gain.setValueAtTime(u,n+g),c<A?(v=c-g,A=Math.pow(10,v/(A-g)*Math.log10(f.sustain))):(v=A-g,A=f.sustain),u*=A,p.gain.exponentialRampToValueAtTime(u,
n+g+v));p.gain.setValueAtTime(u,n+c);g=n+c+(100+20*Math.log10(u))/100*f.release;p.gain.exponentialRampToValueAtTime(1E-5,g);m?(D.connect(F),F.connect(t||p)):D.connect(t||p);t&&t.connect(p);y?(p.connect(w),w.connect(x.destination)):p.connect(x.destination);D.start(n);y&&q.start(n+f.lfodel);B&&r.start(n);D.stop(g);y&&q.stop(g);B&&r.stop(g)}}else 0!=M&&(w=a/1E3,q=(f-1)/1E3,t=G[h]/127,F=(H[h]-64)/64,r=x.createBufferSource(),r.buffer=na[c],c=x.createGain(),c.gain.setValueAtTime(1E-5,w),p=p*t*.015625,0==
p&&(p=1E-5),c.gain.exponentialRampToValueAtTime(p,w+.001),Q&&(n=x.createStereoPanner(),n.pan.value=F),r.connect(n||c),n&&n.connect(c),c.connect(x.destination),r.start(w),w+=q,c.gain.setValueAtTime(p,w),c.gain.exponentialRampToValueAtTime(1E-5,w+.1),r.stop(w+.1))}});r(e);y+=1}clearTimeout(da);da=setTimeout(ja,b)}else alert("Your browser has no Web Audio API -> no playback.")}function t(a){v.length&&((V=a)?ja():clearTimeout(da))}function C(a){return new Promise(function(b,k){for(var d=atob(a),n=new ArrayBuffer(d.length),
c=new Uint8Array(n),e=0;e<d.length;e++)c[e]=d.charCodeAt(e);x.decodeAudioData(n,function(a){b(a)},function(a){k({err:1,msg:a,data:""})})})}function ra(a){return new Promise(function(b,k){function d(n){var c,e,f,h;c=instData[n];e={attack:c.attack,hold:c.hold,decay:c.decay,sustain:c.sustain,release:c.release,atten:c.atten,filter:c.filter,lfodel:c.lfodel,lfofreq:c.lfofreq,lfo2ptc:c.lfo2ptc,lfo2vol:c.lfo2vol,envatt:c.envatt,envhld:c.envhld,envdec:c.envdec,envsus:c.envsus,envrel:c.envrel,env2flt:c.env2flt,
uselfo:ea&&.008<c.lfofreq&&(0!=c.lfo2ptc||0!=c.lfo2vol),useflt:fa&&16E3>c.filter,useenv:ga&&16E3>c.filter&&0!=c.env2flt};c.loopStart&&(e.loopStart=c.loopStart,e.loopEnd=c.loopEnd);f=c.scale;h=c.tune;for(var p=c.keyRangeLo;p<=c.keyRangeHi;p++)ca[a][p]=Math.pow(Math.pow(2,1/12),(p+h)*f),ba[a][p]=e,ha[128*a+p]=1;C(c.sample).then(function(a){e.buffer=a;n<instData.length-1?d(n+1):(instData="",b("ok"))})["catch"](function(a){k(a)})}ca[a]=[];ba[a]=[];d(1)})}function ta(a){return new Promise(function(b,k){var d=
document.createElement("script");d.src=instUrl+"instr"+a+"mp3.js";d.onload=function(){b("ok");document.head.removeChild(d)};d.onerror=function(b){k({err:2,msg:"could not load "+d.src,data:a})};document.head.appendChild(d)})}function ka(a){void 0==a.err&&(a.err=4,a.msg=a.toString());console.log(a.err+", "+a.msg+", "+a.data);switch(a.err){case 1:alert("Your browser does not support decoding ogg/vorbis -> no playback");break;case 2:a="Loading javascript soundfont failed, instrument "+a.data+"\nfalling back to midi-js";
console.log(a);B.innerHTML+=a.replace("\n","<br>");break;case 3:console.log("Loading midi-js soundfont failed, instrument "+a.data+"\nmsg: "+a.msg);break;case 4:alert(a.msg)}}function L(a){function b(a){return new Promise(function(b,d){if(ia[a])b("ok");else{var k;oa[a]?k="https://rawgit.com/gleitz/midi-js-soundfonts/gh-pages/FluidR3_GM/"+p+"-mp3":(p=a in instTab?instTab[a]:p,k=instUrl+p+"-mp3");B.innerHTML+=", loading: "+a;var g=document.createElement("script");g.src=k+".js";g.onload=function(){ia[a]=
MIDI.Soundfont[p];pa[k]=1;console.log("midi-js instr "+c+" geladen");b("ok")};g.onerror=function(){d({err:3,msg:"could not load:"+k,data:a})};k in pa?b("ok"):document.head.appendChild(g)}})}function d(c){b(c).then(function(){var a=ia[c][f+h].split(",")[1];return C(a)}).then(function(b){na[e]=b;B.innerHTML+=", "+c+":"+q;ha[e]=1;L(a)})["catch"](function(a){ka(a);-1==a.msg.indexOf("gleitz")?(oa[c]=1,B.innerHTML+="<br>loading local midi-js font failed, instrument: "+a.data+"<br>trying Github ...",d(c)):
(alert("loading soundfont from Github failed, giving up."),B.style.display="none")})}var k="C Db D Eb E F Gb G Ab A Bb B".split(" "),e=a.shift();if(e){var c=e>>7,q=e%128,f=k[q%12],h=Math.floor(q/12)-1,p=va[c];aa[c]?L(a):withRT&&!qa[c]?ta(c).then(function(){B.innerHTML+="loading instrument "+c+"<br>";return ra(c)}).then(function(){console.log("instr "+c+" geladen");aa[c]=1;L(a)})["catch"](function(a){ka(a);qa[c]=1;d(c)}):d(c)}else M=1,B.style.display="none",t(1)}function sa(a){a=Object.keys(a).filter(function(a){return!(a in
ha)});a.length?(B.innerHTML="",B.style.display="block",B.style.top=document.scrollingElement.scrollTop+document.documentElement.clientHeight/2.5+"px",L(a)):(M=1,t(1))}function R(a,b,d){function k(b){a.removeEventListener("mousedown",k);a.removeEventListener("touchend",k);console.log("event listeners removed from "+a.nodeName);x&&"suspended"==x.state&&x.resume().then(function(){console.log("resuming audioContext")})}a.addEventListener("mousedown",k);a.addEventListener("touchend",k);a.addEventListener(b,
d)}var I,S,ma,y=0,V=0,da,M=0,v=[],N=[],Z={},Y={},W=[],J=[],P=[],U,X=0,O=[],T=[],x=null,na=[],ha={},K=120,qa={},oa={},aa={},ia=[],la={},G=[],H=[],F=null,B=null,va="acoustic_grand_piano bright_acoustic_piano electric_grand_piano honkytonk_piano electric_piano_1 electric_piano_2 harpsichord clavinet celesta glockenspiel music_box vibraphone marimba xylophone tubular_bells dulcimer drawbar_organ percussive_organ rock_organ church_organ reed_organ accordion harmonica tango_accordion acoustic_guitar_nylon acoustic_guitar_steel electric_guitar_jazz electric_guitar_clean electric_guitar_muted overdriven_guitar distortion_guitar guitar_harmonics acoustic_bass electric_bass_finger electric_bass_pick fretless_bass slap_bass_1 slap_bass_2 synth_bass_1 synth_bass_2 violin viola cello contrabass tremolo_strings pizzicato_strings orchestral_harp timpani string_ensemble_1 string_ensemble_2 synth_strings_1 synth_strings_2 choir_aahs voice_oohs synth_choir orchestra_hit trumpet trombone tuba muted_trumpet french_horn brass_section synth_brass_1 synth_brass_2 soprano_sax alto_sax tenor_sax baritone_sax oboe english_horn bassoon clarinet piccolo flute recorder pan_flute blown_bottle shakuhachi whistle ocarina lead_1_square lead_2_sawtooth lead_3_calliope lead_4_chiff lead_5_charang lead_6_voice lead_7_fifths lead_8_bass__lead pad_1_new_age pad_2_warm pad_3_polysynth pad_4_choir pad_5_bowed pad_6_metallic pad_7_halo pad_8_sweep fx_1_rain fx_2_soundtrack fx_3_crystal fx_4_atmosphere fx_5_brightness fx_6_goblins fx_7_echoes fx_8_scifi sitar banjo shamisen koto kalimba bagpipe fiddle shanai tinkle_bell agogo steel_drums woodblock taiko_drum melodic_tom synth_drum reverse_cymbal guitar_fret_noise breath_noise seashore bird_tweet telephone_ring helicopter applause gunshot".split(" "),
pa={},K=120,ba=[],ca=[],ua=.5/60,Q=1,ea=1,fa=1,ga=1;document.addEventListener("DOMContentLoaded",function(){Array.prototype.slice.call(document.getElementsByClassName("abc")).forEach(function(b,d){var e=b.innerHTML.replace(/&gt;/g,">").replace(/&lt;/g,"<").replace(/&amp;/g,"&");a("%%fullsvg _"+d+"\n"+e,b,0)});document.body.addEventListener("click",function(){V&&t(0)},!1);window.addEventListener("resize",b,!1);B=document.getElementById("comp");var d=window.AudioContext||window.webkitAudioContext;if(x=
void 0!=d?new d:null){x.createStereoPanner||(Q=0);x.createOscillator||(ea=0);x.createBiquadFilter||(fa=0);x.createConstantSource||(ga=0);var d=[],e=0;Q||d.push("Your browser does not support the StereoPanner element");withRT&&!ea&&(d.push("Your browser does not support the Oscillator element"),e=1);withRT&&!fa&&(d.push("Your browser does not support the BiquadFilter element"),e=1);withRT&&!ga&&(d.push("Your browser does not support the ConstantSource element"),e=1);d.length&&alert(d.join("\n")+(e?
"\nThe instrument(s) will sound (very) wrong":""))}else alert("Your browser has no Web Audio API -> no playback.")})})();
